Review one of my past projects
solog0039/trial-test pull request #1
Opened 2022-06-07 22:58 UTC by solog0039

In this project:
1. previous project used
2. acted as code reviewer
3. Check if I have used semantic HTML tags
4. Check if you applied HTML & CSS best practices
5. linters not installed because during trial time we did not use them

2022-06-07 23:16 UTC, solog0039 commented on index.html
> +        <h1>Section 2</h1>
Kindly be informed that the best practice is to use only one h1 in one HTML page, you can use h2, h3, or h4.

2022-06-07 23:50 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @solog0039 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 23:50 UTC, tresorsawasawa commented on index.html
> +        <h1>Section 2</h1>
- **[ **REQUIRED** ]**  I think we can improve this comment message by making it more meaningful to not make someone you're reviewing confused and giving the reason/explanation for the requested change. You can proceed like this:
**`I think it would be better to use...(what you suggest to use or add) and then the reason/explanation of "why" it should be used/added**
A good review message is supposed to include the following aspects:
 >  Stating the aimed problem❗, politely offering a suggestion 😏 and a reason or an explanation for making the requested change.

- [ **OPTIONAL** ] It can also be better to use a couple of emojis and/or gifs in the review message to make the code review more human-friendly 👽🤖.

- **[ **REQUIRED** ]**  Kindly make sure you performed at least 2 comments in the review as required for the projects. i.e. you should add some review comments which have the following aspects: statement of the aimed problem❗, politely offering a suggestion 😏 and a reason or an explanation for making the requested change.

- **[ **REQUIRED** ]** Kindly make sure once you completed your review to add a summary to make your review more professional. I suggest you use one of the summaries templates your received on your previous milestones(projects) or you can even use the current one.

2022-06-08 09:59 UTC, solog0039 reviewed
It would be better  if you make a change  according to the comment marked with [ **REQUIRED** ]

2022-06-08 09:59 UTC, solog0039 commented on index.html
> +        <h1>Section 1</h1>
.[ **REQUIRED** ]  Kindly be informed that the best practice is to use only one h1 in one HTML page which is important for search engine optimizations to find your page in the future. Instead using h2, h3...h6 is best practice

2022-06-08 09:59 UTC, solog0039 commented on style.css
> +}
1.  [ **REQUIRED** ] I would like to suggest you that to add two white space before each line of code, It is best standard for css files and it cause linter error 
2. [ **REQUIRED** ] I would suggest you that to add single line after each brace for clarity and to avoid linter errors

2022-06-08 09:59 UTC, solog0039 commented on index.html
> +            src="https://cdn.freecodecamp.org/testable-projects-fcc/images/product-landing-page-logo.png" />
It would be better if you add "alt" tag. this will display and give information about the image in case the image is not displaying

2022-06-08 10:03 UTC, OmarRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @solog0039 👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse 🌐.

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ used inline comments
- ✔️ requested changes **Politely**
- ✔️ implemented all requested changes in previous review

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 21:23 UTC, merged